# This is a basic workflow that is manually triggered

name: add_device
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      device_name:
        description: input device name
        required: true
        type: string
      device_udid:
        description: input device udid
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_device:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger bitrise workflow
      env:
        bitrise_api_key: ${{ secrets.BITRISE_API_KEY }}
        bitrise_app_slug: "e2ce411a700fac93"
      run: |
        curl -H "Authorization: $bitrise_api_key" https://api.bitrise.io/v0.1/apps/$bitrise_app_slug/builds -d \
        '{
          "build_params":{
            "environments":[ {"mapped_to":"DEVICE_NAME","value":"${{ inputs.device_name }}", "is_expand":false}, {"mapped_to":"DEVICE_UDID","value":"${{ inputs.device_udid }}", "is_expand":false}],
            "workflow_id":"add_device"
          },
          "hook_info":{
            "type":"bitrise"
          }
        }'
