# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      device_name:
        description: input device name
        required: true
        type: string
      device_uuid:
        description: input device uuid
        required: true
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  add_device:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger bitrise workflow
      env:
        bitrise_api_key: ${{ secrets.BITRISE_API_KEY }}
      run: |
        curl --fail -o -X POST -H "Authorization: $bitrise_api_key" "https://api.bitrise.io/v0.1/app/e2ce411a700fac93/build/start.json" -d \
        '{
          "build_params":{
            "environments":[
              {"mapped_to":"DEVICE_NAME","value":"${{ inputs.device_name }}", "is_expand":false},
              {"mapped_to":"DEVICE_UUID","value":"${{ inputs.device_uuid }}", "is_expand":false},
            ],
            "branch": "main",
            "workflow_id":"add_device"
          },
          "hook_info":{
            "type":"bitrise"
          }
        }'
                
